config/routes.rb
Rails.application.routes.draw do
  
=begin
  namespace :store do
  get 'products/new'
  end

  namespace :store do
  get 'products/create'
  end

  namespace :store do
  get 'products/update'
  end

  namespace :store do
  get 'products/edit'
  end

  namespace :store do
  get 'products/destroy'
  end

  namespace :store do
  get 'products/index'
  end

  namespace :store do
  get 'products/show'
  end
=end

  namespace :store do
      resources :carts, :line_items, :products
  end
  
  namespace :admin do
    resources :customers, :categories, :products, :units
  end

  namespace :admin do
    resources :products do
      member do
        get 'children'
      end
    end
  end

end

app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :product_units
	has_many :products, through: :product_units
end

app/controllers/admin/units_controller.rb
class Admin::UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to action: :index, notice: 'Unit was successfully created.' }
        #format.html { redirect_to [:admin, @unit], notice: 'Unit was successfully created.' }
        #format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to [:admin, @unit], notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to admin_units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:title)
    end
end

app/helpers/admin/units_helper.rb
module Admin::UnitsHelper
end

app/views/admin/units/_form.html.haml
= simple_form_for([:admin, @unit], html: {class: "form-horizontal", id: "frm_units"}) do |f|
  = f.error_notification

  .form-group
    = f.label :title, 'Unit Name', :class => "control-label col-sm-2"
    %div{:class => "col-sm-6"}
      = f.input :title, label: false

app/views/admin/units/edit.html.haml
= content_for :header do
  %h1 Editing unit: 

= content_for :buttons do
  <a href="#" onclick="$('#frm_units').submit();">Update</a>
  %span|
  = link_to 'Back', admin_units_path

= render 'form'

/= link_to 'Show', [:admin, @unit]
/\|

app/views/admin/units/index.html.haml
= content_for :header do
  %h1 Units

= content_for :buttons do
  = link_to 'New Unit', new_admin_unit_path, :class => "btn btn-default", :data => {:toggle=>"tooltip"},:title => "Add unit"
  <a class="btn btn-default" href="#" role="button">Options</a>

%table
  %thead
    %tr
      %th Title
      %th
      %th
      
  %tbody
    - @units.each do |unit|
      %tr
        %td= unit.title
        %td= link_to 'Edit', edit_admin_unit_path(unit)
        %td= link_to 'Destroy', [:admin, unit], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/admin/units/new.html.haml
= content_for :header do
  %h1 New unit

= content_for :buttons do
  <a href="#" onclick="$('#frm_units').submit();">Save</a>
  %span|
  = link_to 'Back', admin_units_path

= render 'form'

app/views/admin/units/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @unit.title

= link_to 'Edit', edit_admin_unit_path(@unit)
\|
= link_to 'Back', admin_units_path