config/routes.rb
Rails.application.routes.draw do
  
=begin
  namespace :store do
  get 'products/new'
  end

  namespace :store do
  get 'products/create'
  end

  namespace :store do
  get 'products/update'
  end

  namespace :store do
  get 'products/edit'
  end

  namespace :store do
  get 'products/destroy'
  end

  namespace :store do
  get 'products/index'
  end

  namespace :store do
  get 'products/show'
  end
=end

  namespace :store do
      resources :carts, :line_items, :products
  end
  
  namespace :admin do
    resources :customers, :categories, :products, :units
  end

  namespace :admin do
    resources :products do
      member do
        get 'children'
      end
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to [:admin, @customer], notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to [:admin, @customer], notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to admin_customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:store_name, :first_name, :last_name, :email, :phone, :address, :city, :active)
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_form.html.haml
= simple_form_for [:admin, @customer], html: {class: "form-horizontal", id: "frm_customers"} do |f|
  = f.error_notification

  .form-group
    = f.label :store_name, :class => "control-label col-sm-2"
    %div{:class => "col-sm-6"}
      = f.input :store_name, label: false
  .form-group
    = f.label :first_name, :class => "control-label col-sm-2"
    %div{:class => "col-sm-6"}
      = f.input :first_name, label: false
  .form-group
    = f.label :last_name, :class => "control-label col-sm-2"
    %div{:class => "col-sm-6"}
      = f.input :last_name, label: false
  .form-group
    = f.label :email, :class => "control-label col-sm-2"
    %div{:class => "col-sm-6"}
      = f.input :email, label: false
  .form-group
    = f.label :phone, :class => "control-label col-sm-2"
    %div{:class => "col-sm-6"}
      = f.input :phone, label: false
  .form-group
    = f.label :address, :class => "control-label col-sm-2"
    %div{:class => "col-sm-6"}
      = f.input :address, label: false
  .form-group
    = f.label :city, :class => "control-label col-sm-2"
    %div{:class => "col-sm-6"}
      = f.input :city, label: false
  .form-group
    = f.label :active, :class => "control-label col-sm-2"
    %div{:class => "col-sm-6"}
      = f.input :active, label: false

app/views/admin/customers/edit.html.haml
= content_for :header do
  %h1 Editing customer: 

= content_for :buttons do
  <a href="#" onclick="$('#frm_customers').submit();">Update</a>
  %span|
  = link_to 'Back', admin_customers_path

= render 'form'

/= link_to 'Show', [:admin, @customer]
/\|

app/views/admin/customers/index.html.haml
= content_for :header do
  %h1 Customers

= content_for :buttons do
  = link_to 'New Customer', new_admin_customer_path, :class => "btn btn-default", :data => {:toggle=>"tooltip"},:title => "Add customer"
  <a class="btn btn-default" href="#" role="button">Options</a>

%table{:class => "table"}
  %thead
    %tr
      %th Store name
      %th First name
      %th Last name
      %th Email
      %th Phone
      %th Address
      %th City
      %th Active
      %th
      %th
      
  %tbody
    - @customers.each do |customer|
      %tr
        %td= customer.store_name
        %td= customer.first_name
        %td= customer.last_name
        %td= customer.email
        %td= customer.phone
        %td= customer.address
        %td= customer.city
        %td= customer.active
        %td= link_to 'Edit', edit_admin_customer_path(customer)
        %td= link_to 'Destroy',[:admin, customer], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/admin/customers/new.html.haml
= content_for :header do
  %h1 New customer

= content_for :buttons do
  <a href="#" onclick="$('#frm_customers').submit();">Save</a>
  %span|
  = link_to 'Back', admin_customers_path

= render 'form'

app/views/admin/customers/show.html.haml
%p#notice= notice

%p
  %b Store name:
  = @customer.store_name
%p
  %b First name:
  = @customer.first_name
%p
  %b Last name:
  = @customer.last_name
%p
  %b Email:
  = @customer.email
%p
  %b Phone:
  = @customer.phone
%p
  %b Address:
  = @customer.address
%p
  %b City:
  = @customer.city
%p
  %b Active:
  = @customer.active

= link_to 'Edit', edit_admin_customer_path(@customer)
\|
= link_to 'Back', admin_customers_path