config/routes.rb
Rails.application.routes.draw do
  
=begin
  namespace :store do
  get 'products/new'
  end

  namespace :store do
  get 'products/create'
  end

  namespace :store do
  get 'products/update'
  end

  namespace :store do
  get 'products/edit'
  end

  namespace :store do
  get 'products/destroy'
  end

  namespace :store do
  get 'products/index'
  end

  namespace :store do
  get 'products/show'
  end
=end

  namespace :store do
      resources :carts, :line_items, :products
  end
  
  namespace :admin do
    resources :customers, :categories, :products, :units
  end

  namespace :admin do
    resources :products do
      member do
        get 'children'
      end
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories#, join_table: :categories_products
  belongs_to :provider
  has_many :product_units #, inverse_of: :product
  has_many :units, through: :product_units
  has_many :line_items
    
  accepts_nested_attributes_for :product_units

  before_destroy :ensure_not_referenced_by_any_line_items

  #validates :title, :description, :provider_id, :active, presence: true
  
  has_attached_file :image,
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }
  
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
  def s3_credentials
    {:bucket => "geekseed-gs01", :access_key_id => "AKIAIRYXHUSFCNZEZ7IQ", :secret_access_key => "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"}
  end

  private

  	def ensure_not_referenced_by_any_line_items
  		if line_items.empty?
  			return true
  		else
  			errors.add(:base, 'Line Items present')
  			return false
  		end
  	end
  	
  	def self.search_by_category(category_name)
        if category_name
            @category_id = Category.where("title = ?", category_name).take
            if @category_id
                where("category_id = ?", @category_id)
            end
        else
            find(:all)
        end
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:provider_id]
      @products = Product.where(provider_id: params[:provider_id])
    else
      @products = Product.all
    end
    
    if params.has_key?(:search)
        @products = Product.search_by_category(params[:search])
        if !@products
            @products = Product.all
        end
    end
  end
  

  # GET /products/1
  # GET /products/1.json
  def show
  end
  
  # GET /products/new
  def new
    @product = Product.new
    @nodes = Category.roots
    @product_unit = @product.product_units.build
    #@selected_categories = Category.all
    #@unit_options = Unit.all.map{|u| [ u.title, u.id ] }
  end

  # GET /products/1/edit
  def edit
      #p = ProductUnit.select("unit_id, price,description").where("product_id = '%#{params[:id]}%'")

    #Rails.logger.debug("RESULT: #{p}")
    @nodes = Category.roots
    @product_unit = @product.product_units.build
    #@product_unit = @product.product_units.build(:unit_id => 2, :price => 38.5, :description => "just desc")
    
    #Rails.logger.debug("params in UPDATE: #{params}")
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to action: :index, notice: 'Product was successfully created.' }
        #format.html { redirect_to [:admin, @product], notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        Rails.logger.debug("ERROR : #{@product.errors.full_messages}")
        @product_unit = @product.product_units.new
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        @product_unit = @product.product_units.build
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def children
    @product = Product.new
    @nodes = Category.find(params[:id].to_i).children
    render layout: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit( :image, :title, :description, { :category_ids => [] }, :provider_id, :active, product_units_attributes: [:product_id, :unit_id, :price, :description])
    end
end

app/controllers/store/products_controller.rb
class Store::ProductsController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/store/products_helper.rb
module Store::ProductsHelper
end

app/views/admin/products/_form.html.haml
= content_for :javascript do
  :javascript
      var table = $("#tb_categories");
      
      table.treetable({
        expandable: true,
        onNodeCollapse: function() {
          var node = this;
          table.treetable("unloadBranch", node);
        },
        onNodeExpand: function() {
          var node = this;
          // Render loader/spinner while loading
          $.ajax({
            async: false, // Must be false, otherwise loadBranch happens after showChildren?
            url: "/admin/products/" + node.id + "/children"
          }).done(function(html) {
            var rows = $(html).filter("tr");
  
            table.treetable("loadBranch", node, rows);
          });
        }
      });
      
      function addCategories()
      {
        var checkboxes = $('#tb_categories').find('input[type="checkbox"]:checked');
        $('#div-selected-categs').empty();
        $('#div-selected-categs').append(checkboxes.length + ' categories selected'); 
      }

.nav-tabs-custom
  .tabpanel
    %ul{:class => "nav nav-tabs", :role => "tablist", :id => "myTab"}
      %li{:class => "active"}
        %a{:href => "#general", :role => "tab", 'data-toggle' => 'tab'}General
      %li
        %a{:href => "#images", :role => "tab", 'data-toggle' => 'tab'}Images
      %li
        %a{:href => "#data", :role => "tab", 'data-toggle' => 'tab'}Data

  = simple_form_for [:admin, @product], html: {class: "form-horizontal", multipart: true, id: "frm_products"} do |f|
    %div{:class => "tab-content"}
      %div{:class => "tab-pane active", :id => "general", :role => 'tabpanel'}
        .form-group
          = f.label :title, 'Name', :class => "control-label col-sm-2"
          %div{:class => "col-sm-6"}
            = f.input :title, label: false
        .form-group
          = f.label 'Categories', :class => "control-label col-sm-2"
          %div{:class => "col-sm-6"}
            %a{:class => 'btn btn-default', 'data-toggle' => 'modal', 'data-target' => '.bs-example-modal-lg'}
              %i{:class => 'glyphicon glyphicon-plus'} Add Categories
        .form-group
          %label{:class => "control-label col-sm-2"}
          %div{:class => "col-sm-6", :id => "div-selected-categs"}

        .form-group
          = f.label :description, :class => "control-label col-sm-2"
          %div{:class => "col-sm-6"}
            = f.input :description, label: false
        .form-group
          = f.label :provider, :class => "control-label col-sm-2"
          %div{:class => "col-sm-6"}
            = f.association :provider, label_method: :company_name, value_method: :id, label: false
        .form-group
          = f.label 'Product Image:', :class => "control-label col-sm-2"
          %div{:class => "col-sm-6"}
            = f.file_field :image

        = f.simple_fields_for :product_units, @product_unit do |pu|
          .form-group
            = pu.label :title, 'Unit Type', :class => "control-label col-sm-2"
            %div{:class => "col-sm-6"}
              = pu.collection_select :unit_id, Unit.all, :id, :title, :prompt => "Select your unit"
          .form-group
            = pu.label :price, 'Price Value', :class => "control-label col-sm-2"
            %div{:class => "col-sm-6"}
              = pu.input :price, label: 'Price Value', label: false
          .form-group
            = pu.label :description, 'Price Description', :class => "control-label col-sm-2"
            %div{:class => "col-sm-6"}
              = pu.input :description, label: 'Price Description', label: false
          .form-group
            = pu.label :amount, 'In Stock', :class => 'control-label col-sm-2'
            %div{:class => 'col-sm-6'}
              = pu.input :amount, label: false
        .form-group
          = f.label :active, :class => "control-label col-sm-2"
          %div{:class => "col-sm-6"}
            = f.input :active, label: false

      %div{:class => "tab-pane", :id => "images", :role => "tabpanel"}
        %h3 This is a heading test for IMAGES
      %div{:class => "tab-pane", :id => "data", :role => "tabpanel"}
        %h3 Data Information

    %div{:id => 'allCategories', :class => 'modal bs-example-modal-lg', :role => 'dialog', 'data-backdrop' => 'static'}
      .modal-dialog.modal-lg
        .modal-content
          .modal-header
            %button{:type => 'button', :class => 'close', 'data-dismiss' => 'modal', 'aria-label' => 'close'}
              %span{'aria-hidden' => 'true'}x
            %h4{:class => 'modal-title'} Add Categories
          .modal-body
            %table{:id => 'tb_categories', :class => "table row-border hover"}
              %thead
                %tr
                  %th{:width => "100px"}
                    %input{:type => "checkbox"}
                  %th Categories
                  %th{:width => "50px"}
                    Products
              %tbody
                = render :partial => "node", :collection => @nodes, :as => :category
          .modal-footer
            %button{:type => 'button', :class => 'btn btn-default', 'data-dismiss' => 'modal'}Close
            %button{:type => 'button', :class => 'btn btn-default', :onclick => 'addCategories();'} Add Categories

app/views/admin/products/_node.html.haml
%tr{ 'data-tt-id' => "#{category.id}", 'data-tt-parent-id' => "#{category.parent_id}", 'data-tt-branch' => "#{category.has_children}"}
  %td
    = check_box_tag "product[category_ids][]", category.id, @product.categories.include?(category), :id => "#{category.id}"
  %td
    %label{:for => "#{category.id}"}= category.title
  %td
    = category.product_count

app/views/admin/products/children.html.haml
= render :partial => "node", :collection => @nodes, :as => :category

app/views/admin/products/edit.html.haml
= content_for :header do
  %h1 Editing product:

= content_for :buttons do
  <a href="#" onclick="$('#frm_products').submit();">Update</a>
  %span|
  = link_to 'Back', admin_products_path

= render 'form'

/= link_to 'Show', [:admin, @product]
/\|

app/views/admin/products/index.html.haml
= content_for :header do
  %h1 Products

= content_for :buttons do
  = link_to 'New Product', new_admin_product_path, :class => "btn btn-default", :data => {:toggle=>"tooltip"},:title => "Add product"
  <a class="btn btn-default" href="#" role="button">Options</a>

= content_for :javascript do
  :javascript
    function getValue(selectTag) {
      var pid = selectTag.attributes['data-p'].value;
      var price = $('#' + selectTag.attributes['id'].value).find('option[value="' + selectTag.value +'"]').attr('price')
      var qty = $('#' + selectTag.attributes['id'].value).find('option[value="' + selectTag.value +'"]').attr('qty');
      $('#lblPrice_' + pid).text(price);
      $('#lblQty_' + pid).text(qty);
    }
    
    $(document).ready( function () {
      $('#tb_products').DataTable({ searching: false });
    });

= form_tag(admin_products_path, method: "get") do
  %p
    = text_field_tag :search, params[:search]
    = submit_tag "Search by Category", :name => nil

%table.table.row-border.hover#tb_products
  %thead
    %tr
      %th
      %th Image
      %th Name
      %th CODE
      %th Units
      %th Price
      %th Quantity
      %th Status
      %th.col-md-1

  %tbody
    - @products.each do |product|
      %tr
        %td
          %input{:type => "checkbox"}
        %td= image_tag(product.image.url, size: "50x50")
        %td= product.title
        %td= product.product_code
        -units_array = ProductUnit.includes(:unit).where("product_units.product_id = ?", product.id).order('units.title ASC')
        -options = ""
        - units_array.each do |pu|
          -options = options + "<option value='#{pu.unit.id}' price='#{pu.price}' qty='#{pu.amount}'>#{pu.unit.title}</option>"

        %td= select_tag(:id, options.html_safe, :id => "id_#{product.id}", 'data-p' => "#{product.id}", :onchange => "getValue(this);")
        %td= label_tag "", "#{units_array.first.price}", :id => "lblPrice_#{product.id}" 
        %td= label_tag "", "#{units_array.first.amount}", :id => "lblQty_#{product.id}" 
        %td= product.active
        %td
          .btn-group
            %a{:class => 'button btn btn-sm btn-default dropdown-toggle', :href => '#', 'data-toggle' => 'dropdown', 'aria-expanded' => 'false'}
              %i{:class => 'glyphicon glyphicon-cog'}
              %span{:class => 'caret'}
            %ul{:class => 'dropdown-menu'}
              %li
                = link_to 'Edit', edit_admin_product_path(product)
              %li
                = link_to 'Destroy', [:admin, product], :method => :delete, :data => { :confirm => 'Are you sure?' }
%br

app/views/admin/products/new.html.haml
= content_for :header do
  %h1 New product
  
= content_for :buttons do
  <a href="#" onclick="$('#frm_products').submit();">Save</a>
  %span|
  = link_to 'Back', admin_products_path

= render 'form'

app/views/admin/products/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @product.title
%p
  %b Description:
  = @product.description
%p
  %b Provider:
  = @product.provider
%p
  %b Category:
  = @product.category
%p
  %b Active:
  = @product.active

= link_to 'Edit', edit_admin_product_path(@product)
\|
= link_to 'Back', admin_products_path