config/routes.rb
Rails.application.routes.draw do
  
=begin
  namespace :store do
  get 'products/new'
  end

  namespace :store do
  get 'products/create'
  end

  namespace :store do
  get 'products/update'
  end

  namespace :store do
  get 'products/edit'
  end

  namespace :store do
  get 'products/destroy'
  end

  namespace :store do
  get 'products/index'
  end

  namespace :store do
  get 'products/show'
  end
=end

  namespace :store do
      resources :carts, :line_items, :products
  end
  
  namespace :admin do
    resources :customers, :categories, :products, :units
  end

  namespace :admin do
    resources :products do
      member do
        get 'children'
      end
    end
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item = line_items.find_by(product_id: product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end

end

app/models/category.rb
class Category < ActiveRecord::Base
 include ActsAsTree
  
	#has_one :category, foreign_key: 'parent_id'
	has_and_belongs_to_many :products#, join_table: :categories_products
	belongs_to :provider
	
	acts_as_tree order: "title"
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories#, join_table: :categories_products
  belongs_to :provider
  has_many :product_units #, inverse_of: :product
  has_many :units, through: :product_units
  has_many :line_items
    
  accepts_nested_attributes_for :product_units

  before_destroy :ensure_not_referenced_by_any_line_items

  #validates :title, :description, :provider_id, :active, presence: true
  
  has_attached_file :image,
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }
  
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
  def s3_credentials
    {:bucket => "geekseed-gs01", :access_key_id => "AKIAIRYXHUSFCNZEZ7IQ", :secret_access_key => "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"}
  end

  private

  	def ensure_not_referenced_by_any_line_items
  		if line_items.empty?
  			return true
  		else
  			errors.add(:base, 'Line Items present')
  			return false
  		end
  	end
  	
  	def self.search_by_category(category_name)
        if category_name
            @category_id = Category.where("title = ?", category_name).take
            if @category_id
                where("category_id = ?", @category_id)
            end
        else
            find(:all)
        end
    end
end

app/models/product_unit.rb
class ProductUnit < ActiveRecord::Base
  belongs_to :product
  belongs_to :unit
  
  #validates_presence_of :product, :unit
  validates :price, :description, presence: true
  
  #validates :product, presence: true
  #validates :unit_id, presence: true
  #validates :price, presence: true
  #validates :price_description, presence: true
  #validates_associated :product
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	has_many :products
	has_many :categories
end

app/models/store.rb
module Store
  def self.table_name_prefix
    'store_'
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :product_units
	has_many :products, through: :product_units
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   layout 'admin'
   
   #before_filter :require_admin_user
  
   # Prevent CSRF attacks by raising an exception.
   # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :exception
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:company_name, :contact_first_name, :contact_last_name, :city, :phone, :email, :logo_url, :website, :active)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/units_helper.rb
module Admin::UnitsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/store/carts_helper.rb
module Store::CartsHelper
end

app/helpers/store/line_items_helper.rb
module Store::LineItemsHelper
end

app/helpers/store/products_helper.rb
module Store::ProductsHelper
end

app/views/layouts/admin.html.haml
!!! 5
%html
%head
  %title Gs01
  = stylesheet_link_tag    'admin/admin.css', media: 'all'
  /= stylesheet_link_tag    '//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css', media: 'all'
  //= stylesheet_link_tag    '//code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css', media: 'all'
  /= stylesheet_link_tag    'admin/AdminLTE.css', media: 'all'
  /= stylesheet_link_tag    '//cdn.datatables.net/1.10.4/css/jquery.dataTables.css'
  /= stylesheet_link_tag    'admin/jquery.treetable.css'
  /= stylesheet_link_tag    'admin/jquery.treetable.theme.default.css'
  /= javascript_include_tag 'admin/app.js'
  /= javascript_include_tag '//cdn.datatables.net/1.10.4/js/jquery.dataTables.js'
  = csrf_meta_tags

%body{:class => "skin-blue"}
  %header{:class => "header"}
    %a{:href => "", :class => "logo"} Admin Site

    %nav{:class => "navbar navbar-static-top", :role => "navigation"}
      %a{:href => "#", :class => "navbar-btn sidebar-toggle", "data-toggle" => "offcanvas", :role => "button"}
        %span{:class => "sr-only"}Toggle navigation
        %span{:class => "icon-bar"}
        %span{:class => "icon-bar"}
        %span{:class => "icon-bar"}

      .navbar-right
        %ul{:class => "nav navbar-nav"}
          %li{:class => "dropdown messages-menu"}
            %a{:href => "#", :class => "dropdown-toggle", "data-toggle" => "dropdown"}
              %i{:class => "fa fa-envelope"}
              %span{:class => "label label-success"}4
  %div{:class => "wrapper row-offcanvas row-offcanvas-left"}
    %aside{:class => "left-side sidebar-offcanvas"}
      %section{:class => "sidebar"}
        %ul{:class => "sidebar-menu"}
          %li{:class => "treeview"}
            %a{:href => "#"}
              %i{:class => "fa fa-bar-chart-o"}
              %span Products
              %i{:class => "fa fa-angle-left pull-right"}
            %ul{:class => "treeview-menu"}
              %li
                %a{:href =>"#{admin_products_path}"}
                  %i{:class => "fa fa-angle-double-right"} Products
              %li
                %a{:href =>"#{admin_categories_path}"}
                  %i{:class => "fa fa-angle-double-right"} Categories
              %li
                %a{:href =>"#{admin_units_path}"}
                  %i{:class => "fa fa-angle-double-right"} Units
          %li{:class => "treeview"}
            %a{:href => "#"}
              %i{:class => "fa fa-bar-chart-o"}
              %span Customers
              %i{:class => "fa fa-angle-left pull-right"}
            %ul{:class => "treeview-menu"}
              %li
                %a{:href =>"#{admin_customers_path}"}
                  %i{:class => "fa fa-angle-double-right"} Customers
    %aside.right-side
      %section.content-header
        = yield :header
        %div.breadcrumb
          = yield :buttons
      %section.content
        = yield
  /= javascript_include_tag 'admin/jquery.treetable.js'
  = javascript_include_tag 'admin/admin.js'
  = yield :javascript